// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9yJVWVZ4naHWs3KnAlNHLSuAJCTCnyjk',
    appId: '1:554837186768:android:5419247f1a61d7212826d5',
    messagingSenderId: '554837186768',
    projectId: 'sociotopia-ecfa8',
    storageBucket: 'sociotopia-ecfa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsadqieCRSDeorti0vgC7_VFqCFtEJc1k',
    appId: '1:554837186768:ios:25c8dd19378ccc332826d5',
    messagingSenderId: '554837186768',
    projectId: 'sociotopia-ecfa8',
    storageBucket: 'sociotopia-ecfa8.appspot.com',
    androidClientId: '554837186768-lpjjh3sgriatjtcnmrtqb8celr6fnhub.apps.googleusercontent.com',
    iosClientId: '554837186768-01ddhhija4lbfa49ntuck1erh8oq7amo.apps.googleusercontent.com',
    iosBundleId: 'com.example.sociotopia',
  );
}
